// bun run scripts/tap-cask.ts <version> <checksums.txt> — print Casks/konvoy.rb for the tap,
// in the shape the tap's other casks already have (GoReleaser's homebrew_casks output).
import { TARGETS, assetName } from './release'

const [version, checksumsPath] = Bun.argv.slice(2)
if (!version || !checksumsPath) {
  console.error('usage: bun run scripts/tap-cask.ts <version> <checksums.txt>')
  process.exit(2)
}
const sums = new Map<string, string>()
for (const line of (await Bun.file(checksumsPath).text()).trim().split('\n')) {
  const [sha, name] = line.trim().split(/\s+/)
  if (sha && name) sums.set(name, sha)
}
const entry = (os: 'darwin' | 'linux', arch: 'amd64' | 'arm64'): string => {
  const t = TARGETS.find((x) => x.os === os && x.arch === arch)!
  const sha = sums.get(assetName(t))
  if (!sha) throw new Error(`no checksum for ${assetName(t)}`)
  return `      sha256 "${sha}"\n      url "https://github.com/doguyilmaz/konvoy/releases/download/v#{version}/${assetName(t)}"`
}
const caveats = [
  'konvoy drives the agent CLIs you already have. Install whichever you use:',
  '  claude, codex, kiro-cli, opencode',
  'Each authenticates itself; konvoy never handles credentials.',
].map((l) => `    ${l}`).join('\n')
console.log(`# Generated by konvoy's release workflow. DO NOT EDIT.
cask "konvoy" do
  version "${version}"

  on_macos do
    on_intel do
${entry('darwin', 'amd64')}
    end
    on_arm do
${entry('darwin', 'arm64')}
    end
  end

  on_linux do
    on_intel do
${entry('linux', 'amd64')}
    end
    on_arm do
${entry('linux', 'arm64')}
    end
  end

  name "konvoy"
  desc "One session across Claude Code, Codex, Kiro CLI and opencode"
  homepage "https://github.com/doguyilmaz/konvoy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "konvoy"

  caveats <<~EOS
${caveats}
  EOS
end`)
